import Head from "next/head";
import Topo from "../componentes/Topo";
import SecaoCapa from "@/componentes/SecaoCapa";
import SecaoProdutos from "@/componentes/SecaoProdutos";
import SecaoSobre from "@/componentes/SecaoSobre";
import SecaoContatos from "@/componentes/SecaoContatos";
import Rodape from "@/componentes/Rodape";

export default function Home() {
  return (
    <div>
      
      <Head>
        <title>Óticas Vida - Loja de Óculos</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div>
        <Topo />
        <SecaoCapa />
        <SecaoProdutos />
        <SecaoSobre />
        <SecaoContatos />
        <Rodape />
      </div>

    
    </div>
  );
}
